#!/bin/bash

HOME_DIR='/home/bitergia'
CONF_DIR="$HOME_DIR/conf"
CONF_LIST="${MORDRED_CONF_FILES:-$CONF_DIR/setup.cfg}"

rm -f /tmp/.mordred_healthcheck
rm -f /tmp/perceval_*

touch /home/bitergia/logs/all.log && tail -f /home/bitergia/logs/all.log &

sirmordred -c ${CONF_LIST}
